import type { Metadata } from 'next';
import { Poppins } from 'next/font/google';
import '@app/globals.css';

// Components
import { Header } from '@components/navigation/Header';
import { Providers } from '@components/Providers';
import { Footer } from '@components/navigation/Footer';

const poppins = Poppins({
  subsets: ['latin'],
  weight: ['200', '300', '400', '500', '600', '700', '800', '900'],
});
export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

interface IRootLayout {
  children: React.ReactNode;
}

export default function RootLayout({ children }: Readonly<IRootLayout>) {
  return (
    <html suppressHydrationWarning lang="en">
      <body className={poppins.className}>
        <Providers>
          {' '}
          <main className="flex flex-col items-center justify-center  bg-background text-foreground">
            <Header />
            {children}
            <Footer />
          </main>
        </Providers>
      </body>
    </html>
  );
}
