import type { Metadata } from 'next';
import { Poppins } from 'next/font/google';
import '@app/globals.css';

// Components
import { Header } from '@components/navigation/header';

const poppins = Poppins({
  subsets: ['latin'],
  weight: ['400', '500', '600', '700', '800', '900'],
});
export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="light">
      <body className={poppins.className}>
        <main className="flex flex-col items-center justify-center px-4">
          <Header />
          {children}
        </main>
      </body>
    </html>
  );
}
